### ISSUE TITLE
Interpreter name is incorrectly sent to virtualenv

### ISSUE THREAD

**Issue by facundobatista** [PyAr/fades#116]
See this:

$ ~/devel/reps/fades/bin/fades -v -p ~/devel/reps/python/cpython/python concur_exec.py
*** fades ***  2015-09-22 17:25:11,450  fades              DEBUG    Running Python sys.version_info(major=3, minor=4, micro=0, releaselevel='final', serial=0) on 'linux'
*** fades ***  2015-09-22 17:25:11,450  fades              DEBUG    Starting fades v. 3
*** fades ***  2015-09-22 17:25:11,450  fades              DEBUG    Arguments: Namespace(child_options=[], child_program='concur_exec.py', dependency=None, executable=False, ipython=False, python='/home/facundo/devel/reps/python/cpython/python', quiet=False, remove=None, requirement=None, verbose=True, version=False)
*** fades ***  2015-09-22 17:25:11,451  fades.cache        DEBUG    Using cache index: '/home/facundo/.local/share/fades/venvs.idx'
*** fades ***  2015-09-22 17:25:11,452  fades              DEBUG    Dependencies from source file: {'pypi': [Requirement.parse('aiohttp')]}
*** fades ***  2015-09-22 17:25:11,452  fades              DEBUG    Dependencies from requirements file: {}
*** fades ***  2015-09-22 17:25:11,452  fades              DEBUG    Dependencies from parameters: {}
*** fades ***  2015-09-22 17:25:11,452  fades.helpers      DEBUG    Getting interpreter version for: /home/facundo/devel/reps/python/cpython/python
*** fades ***  2015-09-22 17:25:11,452  fades.helpers      DEBUG    Current interpreter is /usr/bin/python3.4
*** fades ***  2015-09-22 17:25:11,452  fades.exec         DEBUG    Executing external command: ['/home/facundo/devel/reps/python/cpython/python', '-c', "\nimport sys, json\nd = dict(path=sys.executable)\nd.update(zip('major minor micro releaselevel serial'.split(), sys.version_info))\nprint(json.dumps(d))\n"]
*** fades ***  2015-09-22 17:25:11,484  fades.exec         DEBUG    :: {"releaselevel": "alpha", "major": 3, "path": "/home/facundo/devel/reps/python/cpython/python", "serial": 0, "minor": 6, "micro": 0}
*** fades ***  2015-09-22 17:25:11,487  fades.helpers      DEBUG    Interpreter=/home/facundo/devel/reps/python/cpython/python3.6. It is the same as fades?=False
*** fades ***  2015-09-22 17:25:11,487  fades.cache        DEBUG    Searching a venv for reqs: {'pypi': [Requirement.parse('aiohttp')]} and interpreter: /home/facundo/devel/reps/python/cpython/python3.6
*** fades ***  2015-09-22 17:25:11,488  fades.cache        DEBUG    No matching venv found :(
*** fades ***  2015-09-22 17:25:11,489  fades.envbuilder   DEBUG    Env will be created at: /home/facundo/.local/share/fades/65af1408-2ca8-4b37-b894-ea27327b753e
*** fades ***  2015-09-22 17:25:11,489  fades.envbuilder   DEBUG    Creating virtualenv with virtualenv
*** fades ***  2015-09-22 17:25:11,490  fades.exec         DEBUG    Executing external command: ['virtualenv', '--python', '/home/facundo/devel/reps/python/cpython/python3.6', '--no-pip', '/home/facundo/.local/share/fades/65af1408-2ca8-4b37-b894-ea27327b753e']
*** fades ***  2015-09-22 17:25:11,532  fades.exec         DEBUG    :: The executable /home/facundo/devel/reps/python/cpython/python3.6 (from --python=/home/facundo/devel/reps/python/cpython/python3.6) does not exist
*** fades ***  2015-09-22 17:25:11,536  fades.envbuilder   ERROR    Error creating virtualenv:  Command '['virtualenv', '--python', '/home/facundo/devel/reps/python/cpython/python3.6', '--no-pip', '/home/facundo/.local/share/fades/65af1408-2ca8-4b37-b894-ea27327b753e']' returned non-zero exit status 3
Traceback (most recent call last):
  File "/home/facundo/devel/reps/fades/fades/envbuilder.py", line 65, in create_with_virtualenv
    helpers.logged_exec(args)
  File "/home/facundo/devel/reps/fades/fades/helpers.py", line 47, in logged_exec
    raise subprocess.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--python', '/home/facundo/devel/reps/python/cpython/python3.6', '--no-pip', '/home/facundo/.local/share/fades/65af1408-2ca8-4b37-b894-ea27327b753e']' returned non-zero exit status 3

It should NOT be /home/facundo/devel/reps/python/cpython/python3.6, just /home/facundo/devel/reps/python/cpython/python

**Comment by facundobatista** [comment]
<GiLgAmEzH> Facu: estaba mirando https://github.com/PyAr/fades/issues/116
<GiLgAmEzH> el tema es que https://github.com/PyAr/fades/blob/master/tests/test_helpers.py#L79
<Facu> GiLgAmEzH, para qué le ponemos el numerito ahí?
<GiLgAmEzH> estoy pensando por qué hice eso. creo que tiene que ver con que queria evitar llamar a /bin/python
<GiLgAmEzH> Facu: estoy tratando de recordar por qué hice eso y no me acuerdo. le doy un par de vueltas a ver si encuentro un caso donde se rompa y armo un PR en un rato
<Facu> GiLgAmEzH, creo que el "ponerle el numerito" iba por el lado de marcar los venvs por intérprete y que no se crucen
<Facu> GiLgAmEzH, pensalo por este lado, a ver qué pasa: más allá del name mangling que hagamos nosotros para lo que lo hagamos, tratemos de pasarle en el --python a virtualenv de la forma menos tocada posible
<Facu> GiLgAmEzH, lo que pasa es que nosotros soportamos "--python=python2", pero eso no se lo banca venv, hay que encontrar un balance ahi
<GiLgAmEzH> Facu: si. creo que el problema está en hacer diferencia entre lo que guardamos y la data con la que llamamos a virtualenv
<Facu> GiLgAmEzH, mirá
<Facu> GiLgAmEzH, http://linkode.org/TekBtuXZ3oariuDbYjElW6
<Facu> GiLgAmEzH, quizás el path que sacamos de ahí es lo que le tenemos que pasar a virtualenv, y listo
<Facu> GiLgAmEzH, porque es lo "menos toqueteado", pero al mismo tiempo soportamos no tener que poner el fullpath como requiere virtualenv
<GiLgAmEzH> Facu: si.
