### ISSUE TITLE
Allow URL as requirement file

### ISSUE THREAD

**Issue by humitos** [PyAr/fades#166]
I think it's a good idea to be able to use an URL for a `requirements.txt`
```
[12:56] humitos: fades> fades -r https://raw.githubusercontent.com/edvm/pysenteishon/master/requirements.txt -x pysenteishon
Traceback (most recent call last):
  File "/home/humitos/.virtualenvs/fades/bin/fades", line 33, in <module>
    main.go(sys.argv)
  File "/home/humitos/.virtualenvs/fades/lib/python3.4/site-packages/fades/main.py", line 166, in go
    reqfile_deps = parsing.parse_reqfile(args.requirement)
  File "/home/humitos/.virtualenvs/fades/lib/python3.4/site-packages/fades/parsing.py", line 186, in parse_reqfile
    with open(filepath, 'rt', encoding='utf8') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'https://raw.githubusercontent.com/edvm/pysenteishon/master/requirements.txt'
[12:56] humitos: fades> 
```

`pip` allows doing this without problem. Maybe we can borrow their source code:
* https://github.com/pypa/pip/blob/develop/pip/download.py#L380

My awful workaround:

    wget https://raw.githubusercontent.com/edvm/pysenteishon/master/requirements.txt -O /tmp/req.txt ; fades -r /tmp/req.txt -x pysenteishon

**Comment by humitos** [comment]
Thinking a little more, I'm not sure if this will be useful. In this case, `pysenteishon` is not a PyPI package and should be installed by hand running `setup.py`, so, after installing the dependencies by providing the external `requirements.txt` there is no way to install `pysenteishon` inside the venv created by fades.

So, is there a way to *install* with fades a software like this one that is not packaged on PyPI? Maybe this is the first question to answer.

**Comment by humitos** [comment]
The *easy way* to solve all this is by accepting repository URLs as mentioned in #7. So, this issue will be closed and this discussion will be followed in the other one.
