### ISSUE TITLE
Running fades without freedesktop.org system

### ISSUE THREAD

**Issue by humitos** [PyAr/fades#20]
I'm running fades in a system without a GUI and I'm getting this error:

```
$ ./fades/bin/fades src/check_python_tutorial.py --email
Traceback (most recent call last):
  File "./fades/bin/fades", line 44, in <module>
    from fades import main
  File "/home/humitos/fades/fades/main.py", line 23, in <module>
    from fades.pipmanager import PipManager
  File "/home/humitos/fades/fades/pipmanager.py", line 22, in <module>
    from xdg import BaseDirectory
ImportError: No module named 'xdg'
$ 
```

**Comment by humitos** [comment]
I just tried the branch `xdg_optional` and I got this error:
```
humitos@manuelkaufmann:~$ ./fades/bin/fades --verbose src/check_python_tutorial.py 
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/handlers.py", line 820, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./fades/bin/fades", line 45, in <module>
    main.go(version, sys.argv)
  File "/home/humitos/fades/fades/main.py", line 97, in go
    l = logger.set_up(log_level)
  File "/home/humitos/fades/fades/logger.py", line 28, in set_up
    handler = logging.handlers.SysLogHandler(address='/dev/log')
  File "/usr/lib/python3.4/logging/handlers.py", line 803, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib/python3.4/logging/handlers.py", line 831, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
humitos@manuelkaufmann:~$
```

**Comment by facundobatista** [comment]
xdg is optional after latest merge
