### ISSUE TITLE
Crash by subprocess.CalledProcessError

### ISSUE THREAD

**Issue by juancarlospaco** [PyAr/fades#230]
``` python
$ uname -a
Linux x 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU/Linux

$ python --version
Python 3.5.2

$ sudo pip install --upgrade pip setuptools wheel virtualenv
Requirement already up-to-date: pip in /usr/lib/python3.5/site-packages
Requirement already up-to-date: setuptools in /usr/lib/python3.5/site-packages
Requirement already up-to-date: wheel in /usr/lib/python3.5/site-packages
Requirement already up-to-date: virtualenv in /usr/lib/python3.5/site-packages

$ sudo pip install fades
[sudo] password for juan: 
Collecting fades
  Downloading fades-5.tar.gz
Building wheels for collected packages: fades
  Running setup.py bdist_wheel for fades ... done
  Stored in directory: /root/.cache/pip/wheels/25/69/a1/4b40c38a9c376b74c4077f7d814c508d6653db97ca51960e22
Successfully built fades
Installing collected packages: fades
Successfully installed fades-5

$ fades --verbose -d fades
*** fades ***  2016-09-10 14:43:04,484  fades              DEBUG    Running Python sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0) on 'linux'
*** fades ***  2016-09-10 14:43:04,484  fades              DEBUG    Starting fades v. 5
*** fades ***  2016-09-10 14:43:04,484  fades              DEBUG    Arguments: Namespace(check_updates=True, child_options=[], child_program=None, dependency=['fades'], executable=False, ipython=False, pip_options=[], python=None, quiet=False, remove=None, requirement=None, system_site_packages=False, verbose=True, version=False, virtualenv_options=[])
*** fades ***  2016-09-10 14:43:04,485  fades.cache        DEBUG    Using cache index: '/home/juan/.local/share/fades/venvs.idx'
*** fades ***  2016-09-10 14:43:04,485  fades              DEBUG    Dependencies from source file: {}
*** fades ***  2016-09-10 14:43:04,485  fades              DEBUG    Dependencies from docstrings: {}
*** fades ***  2016-09-10 14:43:04,485  fades              DEBUG    Dependencies from requirements file: {}
*** fades ***  2016-09-10 14:43:04,487  fades              DEBUG    Dependencies from parameters: {'pypi': [Requirement.parse('fades')]}
*** fades ***  2016-09-10 14:43:04,953  fades.helpers      INFO     There is a new version of fades: 5 and will use it.
*** fades ***  2016-09-10 14:43:04,953  fades.helpers      DEBUG    Getting interpreter version for: None
*** fades ***  2016-09-10 14:43:04,954  fades.helpers      DEBUG    Current interpreter is /usr/bin/python3.5
*** fades ***  2016-09-10 14:43:04,954  fades.cache        DEBUG    Using cache index: '/home/juan/.local/share/fades/venvs.idx'
*** fades ***  2016-09-10 14:43:04,955  fades.cache        DEBUG    Index not found, starting empty
*** fades ***  2016-09-10 14:43:04,955  fades.cache        DEBUG    Searching a venv for reqs: {'pypi': [Requirement.parse('fades==5')]} and interpreter: /usr/bin/python3.5
*** fades ***  2016-09-10 14:43:04,955  fades.cache        DEBUG    No matching venv found :(
*** fades ***  2016-09-10 14:43:04,956  fades.envbuilder   DEBUG    Env will be created at: /home/juan/.local/share/fades/09973ac7-a906-44d4-a523-7920ea701c45
*** fades ***  2016-09-10 14:43:04,957  fades.envbuilder   DEBUG    Creating virtualenv with pyvenv. options=[]
Traceback (most recent call last):
  File "/usr/bin/fades", line 33, in <module>
    main.go(sys.argv)
  File "/usr/lib/python3.5/site-packages/fades/main.py", line 197, in go
    options, pip_options)
  File "/usr/lib/python3.5/site-packages/fades/envbuilder.py", line 123, in create_venv
    env_path, env_bin_path, pip_installed = env.create_env(interpreter, is_current, options)
  File "/usr/lib/python3.5/site-packages/fades/envbuilder.py", line 96, in create_env
    self.create(self.env_path)
  File "/usr/lib/python3.5/venv/__init__.py", line 83, in create
    self._setup_pip(context)
  File "/usr/lib/python3.5/venv/__init__.py", line 255, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/juan/.local/share/fades/09973ac7-a906-44d4-a523-7920ea701c45/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1

$ fades --verbose -d requests
*** fades ***  2016-09-10 14:44:10,520  fades              DEBUG    Running Python sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0) on 'linux'
*** fades ***  2016-09-10 14:44:10,520  fades              DEBUG    Starting fades v. 5
*** fades ***  2016-09-10 14:44:10,520  fades              DEBUG    Arguments: Namespace(check_updates=False, child_options=[], child_program=None, dependency=['requests'], executable=False, ipython=False, pip_options=[], python=None, quiet=False, remove=None, requirement=None, system_site_packages=False, verbose=True, version=False, virtualenv_options=[])
*** fades ***  2016-09-10 14:44:10,521  fades.cache        DEBUG    Using cache index: '/home/juan/.local/share/fades/venvs.idx'
*** fades ***  2016-09-10 14:44:10,521  fades              DEBUG    Dependencies from source file: {}
*** fades ***  2016-09-10 14:44:10,521  fades              DEBUG    Dependencies from docstrings: {}
*** fades ***  2016-09-10 14:44:10,521  fades              DEBUG    Dependencies from requirements file: {}
*** fades ***  2016-09-10 14:44:10,524  fades              DEBUG    Dependencies from parameters: {'pypi': [Requirement.parse('requests')]}
*** fades ***  2016-09-10 14:44:10,524  fades.helpers      DEBUG    Getting interpreter version for: None
*** fades ***  2016-09-10 14:44:10,524  fades.helpers      DEBUG    Current interpreter is /usr/bin/python3.5
*** fades ***  2016-09-10 14:44:10,524  fades.cache        DEBUG    Using cache index: '/home/juan/.local/share/fades/venvs.idx'
*** fades ***  2016-09-10 14:44:10,524  fades.cache        DEBUG    Index not found, starting empty
*** fades ***  2016-09-10 14:44:10,524  fades.cache        DEBUG    Searching a venv for reqs: {'pypi': [Requirement.parse('requests')]} and interpreter: /usr/bin/python3.5
*** fades ***  2016-09-10 14:44:10,524  fades.cache        DEBUG    No matching venv found :(
*** fades ***  2016-09-10 14:44:10,525  fades.envbuilder   DEBUG    Env will be created at: /home/juan/.local/share/fades/dd0e4d70-5702-4824-9414-a68cf2602874
*** fades ***  2016-09-10 14:44:10,525  fades.envbuilder   DEBUG    Creating virtualenv with pyvenv. options=[]
Traceback (most recent call last):
  File "/usr/bin/fades", line 33, in <module>
    main.go(sys.argv)
  File "/usr/lib/python3.5/site-packages/fades/main.py", line 197, in go
    options, pip_options)
  File "/usr/lib/python3.5/site-packages/fades/envbuilder.py", line 123, in create_venv
    env_path, env_bin_path, pip_installed = env.create_env(interpreter, is_current, options)
  File "/usr/lib/python3.5/site-packages/fades/envbuilder.py", line 96, in create_env
    self.create(self.env_path)
  File "/usr/lib/python3.5/venv/__init__.py", line 83, in create
    self._setup_pip(context)
  File "/usr/lib/python3.5/venv/__init__.py", line 255, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/juan/.local/share/fades/dd0e4d70-5702-4824-9414-a68cf2602874/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1
```
- Print the full path location of the LOG file if any when using `--verbose` please...

**Comment by edvm** [comment]
I am getting the same problem using Fades 5.0:

`
(tero) [edvm@localhost app]$ fades -r requirements.txt 
Traceback (most recent call last):
  File "/home/edvm/Bin/fades/bin/fades", line 33, in <module>
    main.go(sys.argv)
  File "/home/edvm/Bin/fades/fades/main.py", line 225, in go
    options, pip_options)
  File "/home/edvm/Bin/fades/fades/envbuilder.py", line 125, in create_venv
    env_path, env_bin_path, pip_installed = env.create_env(interpreter, is_current, options)
  File "/home/edvm/Bin/fades/fades/envbuilder.py", line 103, in create_env
    self.create(self.env_path)
  File "/usr/lib64/python3.5/venv/__init__.py", line 85, in create
    self._setup_pip(context)
  File "/usr/lib64/python3.5/venv/__init__.py", line 257, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib64/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/edvm/.fades/0571a5dc-b8d8-4f4f-a902-113367b9831a/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1
`

**Comment by edvm** [comment]
```
subprocess.CalledProcessError: Command '['/home/edvm/.fades/0571a5dc-b8d8-4f4f-a902-113367b9831a/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1
(tero) [edvm@localhost app]$ ls /home/edvm/.fades/0571a5dc-b8d8-4f4f-a902-113367b9831a/bin/
python  python3
(tero) [edvm@localhost app]$ /home/edvm/.fades/0571a5dc-b8d8-4f4f-a902-113367b9831a/bin/python3 -Im ensurepip --upgrade --default-pip
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.5/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/usr/lib64/python3.5/ensurepip/__init__.py", line 232, in _main
    default_pip=args.default_pip,
  File "/usr/lib64/python3.5/ensurepip/__init__.py", line 97, in bootstrap
    dep_records = rewheel.find_system_records([p[0] for p in _PROJECTS])
  File "/usr/lib64/python3.5/ensurepip/rewheel/__init__.py", line 39, in find_system_records
    sys_sitepack = site.getsitepackages([sys.base_prefix, sys.base_exec_prefix])
AttributeError: module 'site' has no attribute 'getsitepackages'
(tero) [edvm@localhost app]$
```

**Comment by facundobatista** [comment]
Sorry, I don't understand this issue report.

@juancarlospaco , if I run "fades --verbose -d fades" it works here (using fades 5) ... if you run it in your system it fails? it's reproducible? Also, at the end of the report you say we should report the log place: no needed, we log to /var/log/syslog. 

@edvm , you say you get into the same problem... but I don't understand how to reproduce that problem... fades always explode in your system for any requirement?

Thank you both!!!!

**Comment by juancarlospaco** [comment]
**I can not Reproduce anymore.**

Thanks... :smile_cat: 

```python
juan@x ~  $ fades --verbose -d requests
*** fades ***  2017-04-27 14:48:33,394  fades              DEBUG    Running Python sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0) on 'linux'
*** fades ***  2017-04-27 14:48:33,394  fades              DEBUG    Starting fades v. 5
*** fades ***  2017-04-27 14:48:33,394  fades              DEBUG    Arguments: Namespace(check_updates=False, child_options=[], child_program=None, dependency=['requests'], executable=False, ipython=False, pip_options=[], python=None, quiet=False, remove=None, requirement=None, system_site_packages=False, verbose=True, version=False, virtualenv_options=[])
*** fades ***  2017-04-27 14:48:33,394  fades.cache        DEBUG    Using cache index: '/home/juan/.local/share/fades/venvs.idx'
*** fades ***  2017-04-27 14:48:33,394  fades              DEBUG    Dependencies from source file: {}
*** fades ***  2017-04-27 14:48:33,395  fades              DEBUG    Dependencies from docstrings: {}
*** fades ***  2017-04-27 14:48:33,395  fades              DEBUG    Dependencies from requirements file: {}
*** fades ***  2017-04-27 14:48:33,397  fades              DEBUG    Dependencies from parameters: {'pypi': [Requirement.parse('requests')]}
*** fades ***  2017-04-27 14:48:33,397  fades.helpers      DEBUG    Getting interpreter version for: None
*** fades ***  2017-04-27 14:48:33,397  fades.helpers      DEBUG    Current interpreter is /usr/bin/python3.6
*** fades ***  2017-04-27 14:48:33,397  fades.cache        DEBUG    Using cache index: '/home/juan/.local/share/fades/venvs.idx'
*** fades ***  2017-04-27 14:48:33,398  fades.cache        DEBUG    Searching a venv for reqs: {'pypi': [Requirement.parse('requests')]} and interpreter: /usr/bin/python3.6
*** fades ***  2017-04-27 14:48:33,398  fades.cache        DEBUG    No matching venv found :(
*** fades ***  2017-04-27 14:48:33,398  fades.envbuilder   DEBUG    Env will be created at: /home/juan/.local/share/fades/9fc04480-b2f2-43da-a7ed-6afc32321522
*** fades ***  2017-04-27 14:48:33,399  fades.envbuilder   DEBUG    Creating virtualenv with pyvenv. options=[]
*** fades ***  2017-04-27 14:48:35,464  fades.envbuilder   DEBUG    env_bin_path: /home/juan/.local/share/fades/9fc04480-b2f2-43da-a7ed-6afc32321522/bin
*** fades ***  2017-04-27 14:48:35,464  fades.envbuilder   DEBUG    Installing dependencies for repo 'pypi': requested=[Requirement.parse('requests')]
*** fades ***  2017-04-27 14:48:35,464  fades.pipmanager   INFO     Installing dependency: requests
*** fades ***  2017-04-27 14:48:35,464  fades.exec         DEBUG    Executing external command: ['/home/juan/.local/share/fades/9fc04480-b2f2-43da-a7ed-6afc32321522/bin/pip', 'install', 'requests']
*** fades ***  2017-04-27 14:48:35,916  fades.exec         DEBUG    :: Collecting requests
*** fades ***  2017-04-27 14:48:37,065  fades.exec         DEBUG    ::   Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
*** fades ***  2017-04-27 14:48:38,281  fades.exec         DEBUG    :: Installing collected packages: requests
*** fades ***  2017-04-27 14:48:38,641  fades.exec         DEBUG    :: Successfully installed requests-2.13.0
*** fades ***  2017-04-27 14:48:39,845  fades.pipmanager   DEBUG    getting installed version for requests
*** fades ***  2017-04-27 14:48:39,846  fades.exec         DEBUG    Executing external command: ['/home/juan/.local/share/fades/9fc04480-b2f2-43da-a7ed-6afc32321522/bin/pip', 'show', 'requests']
*** fades ***  2017-04-27 14:48:40,216  fades.exec         DEBUG    :: Name: requests
*** fades ***  2017-04-27 14:48:40,216  fades.exec         DEBUG    :: Version: 2.13.0
*** fades ***  2017-04-27 14:48:40,217  fades.exec         DEBUG    :: Summary: Python HTTP for Humans.
*** fades ***  2017-04-27 14:48:40,217  fades.exec         DEBUG    :: Home-page: http://python-requests.org
*** fades ***  2017-04-27 14:48:40,217  fades.exec         DEBUG    :: Author: Kenneth Reitz
*** fades ***  2017-04-27 14:48:40,217  fades.exec         DEBUG    :: Author-email: me@kennethreitz.com
*** fades ***  2017-04-27 14:48:40,217  fades.exec         DEBUG    :: License: Apache 2.0
*** fades ***  2017-04-27 14:48:40,218  fades.exec         DEBUG    :: Location: /home/juan/.local/share/fades/9fc04480-b2f2-43da-a7ed-6afc32321522/lib/python3.6/site-packages
*** fades ***  2017-04-27 14:48:40,218  fades.exec         DEBUG    :: Requires:
*** fades ***  2017-04-27 14:48:40,316  fades.pipmanager   DEBUG    Installed version of requests is: 2.13.0
*** fades ***  2017-04-27 14:48:40,316  fades.envbuilder   DEBUG    Installed dependencies: {'pypi': {'requests': '2.13.0'}}
*** fades ***  2017-04-27 14:48:40,317  fades.cache        DEBUG    Storing installed={'pypi': {'requests': '2.13.0'}} metadata={'env_path': '/home/juan/.local/share/fades/9fc04480-b2f2-43da-a7ed-6afc32321522', 'env_bin_path': '/home/juan/.local/share/fades/9fc04480-b2f2-43da-a7ed-6afc32321522/bin', 'pip_installed': True} interpreter=/usr/bin/python3.6 options={'pyvenv_options': [], 'virtualenv_options': []}
*** fades ***  2017-04-27 14:48:40,322  fades              DEBUG    Calling the interactive Python interpreter
Python 3.6.0 (default, Jan 16 2017, 12:12:55)
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by juancarlospaco** [comment]
Feel free to re-open if needed @facundobatista @edvm :smile_cat:
