### ISSUE TITLE
Flag -rm seems to not work on Fades 5.0

### ISSUE THREAD

**Issue by edvm** [PyAr/fades#231]
Using:

```
(tero) [edvm@localhost app]$ fades --version
Running 'fades' version 5.0
    Python: sys.version_info(major=3, minor=5, micro=1, releaselevel='final', serial=0)
    System: linux
(tero) [edvm@localhost app]$
```

When i want to remove a virtualenv by its UUID i get the following error:

```
(tero) [edvm@localhost app]$ ls ~/.fades/
216bd505-4e8d-43ff-897c-b61a196d67c0  a763754b-a4dd-4c23-a9b0-2cb15d0ffaab  usage_stats
(tero) [edvm@localhost app]$ fades -rm 216bd505-4e8d-43ff-897c-b61a196d67c0
Traceback (most recent call last):
  File "/home/edvm/Bin/fades/bin/fades", line 33, in <module>
    main.go(sys.argv)
  File "/home/edvm/Bin/fades/fades/main.py", line 183, in go
    indicated_deps = parsing.parse_srcfile(args.child_program)
  File "/home/edvm/Bin/fades/fades/parsing.py", line 240, in parse_srcfile
    with o**pen(filepath, 'rt',** encoding='utf8') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '216bd505-4e8d-43ff-897c-b61a196d67c0'
```

I can confirm that the directory/path exists:

```
(tero) [edvm@localhost app]$ python -c "import os; print(os.path.isdir('/home/edvm/.fades/216bd505-4e8d-43ff-897c-b61a196d67c0'))"
True
```

**Comment by gilgamezh** [comment]
@edvm  the command is `--rm`
