### ISSUE TITLE
Doesn't support for nested requirements.txt

### ISSUE THREAD

**Issue by humitos** [PyAr/fades#236]
If you have a `base.txt`

    requests

and `dev.txt` requirements:

    -r base.txt
    pdbpp

and run `fades -r dev.txt` it doesn't work as expected.

```
[09:12] humitos: tmp> fades --requirement dev.txt 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1137, in parseString
    raise exc
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1127, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1001, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2412, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1001, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2669, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1001, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2395, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1005, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1785, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2788, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 94, in __init__
    requirement_string[e.loc:e.loc + 8]))
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'-r base.'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/humitos/Source/3rdparty/fades/bin/fades", line 33, in <module>
    main.go(sys.argv)
  File "/home/humitos/Source/3rdparty/fades/fades/main.py", line 214, in go
    reqfile_deps = parsing.parse_reqfile(args.requirement)
  File "/home/humitos/Source/3rdparty/fades/fades/parsing.py", line 233, in parse_reqfile
    return _parse_requirement(fh)
  File "/home/humitos/Source/3rdparty/fades/fades/parsing.py", line 212, in _parse_requirement
    parsed_req = parse_fade_requirement(line)
  File "/home/humitos/Source/3rdparty/fades/fades/parsing.py", line 87, in parse_fade_requirement
    dependency = list(parse_requirements(requirement))[0]
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2781, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2790, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'-r base.'"
[09:12] humitos: tmp> 
```

I'm running fades from github master on Xubuntu 16.04

**Comment by gilgamezh** [comment]
As we task at PyConAr it is a bug (or missing feature) and we'll fix it. 

As a workaround you can pass multiples requirements.txt files  `fades -r req.txt -r req_dev.txt....`

thanks!
