### ISSUE TITLE
fades fails installing pbr 3.0 project

### ISSUE THREAD

**Issue by vmalloc** [PyAr/fades#260]
Trying to run cob via `fades -d cob -x cob` yields the following installation error:

```
error in setup command: Error parsing /private/var/folders/hy/gry5dnsj6zlbrclcg160nc800000gn/T/pip-build-id4dwlip/cob/setup.cfg: ModuleNotFoundError: No module named 'setuptools.command.build_clib'
```

The project uses `pbr`, so I'm guessing it has something to do with how fades creates the underlying virtualenv...

**Comment by facundobatista** [comment]
It worked ok in my machine (see [log here](http://linkode.org/#5RonnayuZZyekWzAXFJDH2)). Would you please run the following command and share with us all the output? This way I could start to see what's going on.

`fades -v -d cob -x cob`

 Thanks!

**Comment by vmalloc** [comment]
@facundobatista sure - this is what I'm getting:
```
*** fades ***  2017-06-13 09:10:18,702  INFO     Hi! This is fades 6.0, automatically managing your dependencies
*** fades ***  2017-06-13 09:10:18,702  INFO     Installing dependency: 'cob'
*** fades ***  2017-06-13 09:10:33,905  ERROR    Execution ended in 1 for cmd ['/Users/ry/.fades/c8c84b44-e72e-4dc5-81f1-34fe5e94f483/bin/pip', 'install', 'cob']
*** fades ***  2017-06-13 09:10:33,905  ERROR    :: Collecting cob
*** fades ***  2017-06-13 09:10:33,905  ERROR    ::   Downloading cob-0.13.1.tar.gz (137kB)
*** fades ***  2017-06-13 09:10:33,905  ERROR    ::     Complete output from command python setup.py egg_info:
*** fades ***  2017-06-13 09:10:33,905  ERROR    ::     warning: no files found matching '*' under directory 'setuptools/_vendor'
*** fades ***  2017-06-13 09:10:33,905  ERROR    ::
*** fades ***  2017-06-13 09:10:33,905  ERROR    ::     Installed /private/var/folders/hy/gry5dnsj6zlbrclcg160nc800000gn/T/pip-build-1f7e_scn/cob/.eggs/setuptools-36.0.1-py3.6.egg
*** fades ***  2017-06-13 09:10:33,905  ERROR    ::     Searching for pbr>=1.9
*** fades ***  2017-06-13 09:10:33,905  ERROR    ::     Reading https://pypi.python.org/simple/pbr/
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::     Downloading https://pypi.python.org/packages/18/2e/28a7d361a568b1a6c86946674e8ac35a609573c3a3d12bb20f6aaf1c39bf/pbr-3.0.1.tar.gz#md5=c537dbb9756e319be25772b1fe1c05fa
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::     Best match: pbr 3.0.1
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::     Processing pbr-3.0.1.tar.gz
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::     Writing /var/folders/hy/gry5dnsj6zlbrclcg160nc800000gn/T/easy_install-as2m727u/pbr-3.0.1/setup.cfg
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::     Running pbr-3.0.1/setup.py -q bdist_egg --dist-dir /var/folders/hy/gry5dnsj6zlbrclcg160nc800000gn/T/easy_install-as2m727u/pbr-3.0.1/egg-dist-tmp-g_57mwa6
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::     creating /private/var/folders/hy/gry5dnsj6zlbrclcg160nc800000gn/T/pip-build-1f7e_scn/cob/.eggs/pbr-3.0.1-py3.6.egg
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::     Extracting pbr-3.0.1-py3.6.egg to /private/var/folders/hy/gry5dnsj6zlbrclcg160nc800000gn/T/pip-build-1f7e_scn/cob/.eggs
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::     Installed /private/var/folders/hy/gry5dnsj6zlbrclcg160nc800000gn/T/pip-build-1f7e_scn/cob/.eggs/pbr-3.0.1-py3.6.egg
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::     ERROR:root:Error parsing
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::     Traceback (most recent call last):
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::       File "/private/var/folders/hy/gry5dnsj6zlbrclcg160nc800000gn/T/pip-build-1f7e_scn/cob/.eggs/pbr-3.0.1-py3.6.egg/pbr/core.py", line 111, in pbr
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::         attrs = util.cfg_to_args(path, dist.script_args)
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::       File "/private/var/folders/hy/gry5dnsj6zlbrclcg160nc800000gn/T/pip-build-1f7e_scn/cob/.eggs/pbr-3.0.1-py3.6.egg/pbr/util.py", line 267, in cfg_to_args
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::         wrap_commands(kwargs)
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::       File "/private/var/folders/hy/gry5dnsj6zlbrclcg160nc800000gn/T/pip-build-1f7e_scn/cob/.eggs/pbr-3.0.1-py3.6.egg/pbr/util.py", line 569, in wrap_commands
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::         cmdclass = ep.resolve()
*** fades ***  2017-06-13 09:10:33,906  ERROR    ::       File "/Users/ry/.fades/c8c84b44-e72e-4dc5-81f1-34fe5e94f483/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
*** fades ***  2017-06-13 09:10:33,907  ERROR    ::         module = __import__(self.module_name, fromlist=['__name__'], level=0)
*** fades ***  2017-06-13 09:10:33,907  ERROR    ::     ModuleNotFoundError: No module named 'setuptools.command.build_clib'
*** fades ***  2017-06-13 09:10:33,907  ERROR    ::     error in setup command: Error parsing /private/var/folders/hy/gry5dnsj6zlbrclcg160nc800000gn/T/pip-build-1f7e_scn/cob/setup.cfg: ModuleNotFoundError: No module named 'setuptools.command.build_clib'
*** fades ***  2017-06-13 09:10:33,907  ERROR    ::
*** fades ***  2017-06-13 09:10:33,907  ERROR    ::     ----------------------------------------
*** fades ***  2017-06-13 09:10:33,907  ERROR    :: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hy/gry5dnsj6zlbrclcg160nc800000gn/T/pip-build-1f7e_scn/cob/
```

I have `fades` installed through `homebrew` so perhaps it's related?

**Comment by facundobatista** [comment]
Hi @vmalloc ! Yes, probably the installation method is related, but I still need to understand what's going on.

I will need to ask you for the logs again. Check please the command that I said to run, that includes the "-v", which will put fades in verbose mode and tell us more info.

Thanks!

**Comment by facundobatista** [comment]
OTOH, @vmalloc , probably we don't need the verbose logs (I was asking for them mostly because I didn't understand how fades would produce such error).

I've been trying to analyse the problem, and found that it is unrelated to fades. It looks from other reports that it may be because weird installations in the machine: old pip, old setuptools, another path clashing in the current one, etc. Check these reports:

    https://github.com/manosim/django-rest-framework-docs/issues/120
    https://github.com/pypa/setuptools/issues/937

One way to move forward here is to see if you could install "cob" in a manually created virtualenv. If no, it's totally fades unrelated. If yes, we'd need to start checking versions (like which pip it's being used in each case, which setuptools imported, etc).

Thanks for your time!

**Comment by vmalloc** [comment]
I tried upgrading setuptools, pip and virtualenv in the homebrew environment but it didn't solve the issue:
```
/usr/local/opt/python3/bin/python3.6 -m pip install -U pip setuptools virtualenv
```

When I try with a manually installed env it seems to work just fine:

```
$ python3.6 -m virtualenv /tmp/test_env                                                                                                                                                                             
Using base prefix '/Users/rotemy/.pyenv/versions/3.6.0'
New python executable in /tmp/test_env/bin/python3.6
Also creating executable in /tmp/test_env/bin/python
Installing setuptools, pip, wheel...done.

$ /tmp/test_env/bin/pip install cob
...
Installing collected packages: colorama, PyYAML, kaptan, click, libtmux, tmuxp, vine, amqp, kombu, billiard, pytz, celery, Logbook, emport, sentinels, six, vintage, gossip, Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, Flask-Script, Mako, python-dateutil, SQLAlchemy, python-editor, alembic, Flask-SQLAlchemy, Flask-Migrate, idna, chardet, urllib3, certifi, requests, URLObject, Flask-Loopback, gunicorn, psycopg2, py, pytest, virtualenv, cob
Successfully installed Flask-0.12.2 Flask-Loopback-1.4.5 Flask-Migrate-2.0.4 Flask-SQLAlchemy-2.2 Flask-Script-2.0.5 Jinja2-2.9.6 Logbook-1.0.0 Mako-1.0.6 MarkupSafe-1.0 PyYAML-3.12 SQLAlchemy-1.1.10 URLObject-2.4.3 Werkzeug-0.12.2 alembic-0.9.2 amqp-2.1.4 billiard-3.5.0.2 celery-4.0.2 certifi-2017.4.17 chardet-3.0.4 click-6.7 cob-0.13.1 colorama-0.3.9 emport-1.2.0 gossip-2.2.0 gunicorn-19.7.1 idna-2.5 itsdangerous-0.24 kaptan-0.5.8 kombu-4.0.2 libtmux-0.7.3 psycopg2-2.7.1 py-1.4.34 pytest-3.1.2 python-dateutil-2.6.0 python-editor-1.0.3 pytz-2017.2 requests-2.17.3 sentinels-1.0.0 six-1.10.0 tmuxp-1.3.1 urllib3-1.21.1 vine-1.1.3 vintage-0.3.0 virtualenv-15.1.0
$
```

**Comment by vmalloc** [comment]
Ok, deleting `~/.fades` and trying again solved it. Thanks for the help!

**Comment by facundobatista** [comment]
I wonder which glitch inside .fades was causing the problem :/
