### ISSUE TITLE
fades -x <some python binary name> fails with exception instead of handling file not found

### ISSUE THREAD

**Issue by nessita** [PyAr/fades#303]
nessita@miro:~$ fades -x rst2html5
Traceback (most recent call last):
  File "/usr/bin/fades", line 33, in <module>
    main.go(sys.argv)
  File "/usr/lib/python3/dist-packages/fades/main.py", line 215, in go
    p = subprocess.Popen(cmd + args.child_options)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nessita/.local/share/fades/f28ae7ce-d8eb-4a06-903d-69f75e620b51/bin/rst2html5'

**Comment by facundobatista** [comment]
Solved in fades 7, where a proper message is given
