### ISSUE TITLE
Running fades -p on an existing venv does not adjust the python binary

### ISSUE THREAD

**Issue by nessita** [PyAr/fades#305]
Hi!

So I used fades to test a few things, and I did not notice the default python was python3. I just noticed when I got an error from my dependency:

nessita@miro:~$ fades test-twisted-deps.py 
Traceback (most recent call last):
  File "test-twisted-deps.py", line 2, in <module>
    import gi.pygtkcompat  # fades
  File "/home/nessita/.local/share/fades/af51ce76-4256-4b98-85a5-39a01b98ef17/lib/python3.5/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'

I then re-executed with -p but since the env was already created, the -p option was not honored:

nessita@miro:~$ fades test-twisted-deps.py -p /usr/bin/python
Traceback (most recent call last):
  File "test-twisted-deps.py", line 2, in <module>
    import gi.pygtkcompat  # fades
  File "/home/nessita/.local/share/fades/af51ce76-4256-4b98-85a5-39a01b98ef17/lib/python3.5/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'

The script I used is very dumb:

nessita@miro:~$ cat test-twisted-deps.py 
#!/usr/bin/env python
import gi.pygtkcompat  # fades

from twisted.internet import gireactor  # fades
gireactor.install()

Removing the envs and retrying did not solve the issue:

# no fades envs present
nessita@miro:~$ ls ./.local/share/fades
venvs.idx

# retried
nessita@miro:~$ fades test-twisted-deps.py -p /usr/bin/python
*** fades ***  2018-04-06 16:11:36,954  INFO     Installing dependency: gi
*** fades ***  2018-04-06 16:11:49,550  INFO     Installing dependency: twisted
Traceback (most recent call last):
  File "test-twisted-deps.py", line 2, in <module>
    import gi.pygtkcompat  # fades
  File "/home/nessita/.local/share/fades/a296b7df-19e4-413b-8e29-13de93a9c0f2/lib/python3.5/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'

# /usr/bin/python is python2
nessita@miro:~$ /usr/bin/python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by gilgamezh** [comment]
You are passing the `-p` option to the script. Not to fades

instead of `fades test-twisted-deps.py -p /usr/bin/python`

you should use `fades  -p /usr/bin/python  test-twisted-deps.py`
