### ISSUE TITLE
Error parsing code line which contains fades and #

### ISSUE THREAD

**Issue by malderete** [PyAr/fades#316]
The following code makes fades crash:

```python
import requests  #fades

url = 'http://fades.readthedocs.io/en/release-7-0/readme.html#how-to-use-it'
r = requests.get(url)
print(r.status_code)
```

with the following traceback:
```python
Traceback (most recent call last):
  File "/usr/bin/fades", line 33, in <module>
    main.go()
  File "/usr/lib/python3.6/site-packages/fades/main.py", line 218, in go
    indicated_deps = parsing.parse_srcfile(args.child_program)
  File "/usr/lib/python3.6/site-packages/fades/parsing.py", line 241, in parse_srcfile
    return _parse_content(fh)
  File "/usr/lib/python3.6/site-packages/fades/parsing.py", line 111, in _parse_content
    import_part, fades_part = import_part.rsplit("#", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

The exceptions seems to be raised in the line which contains the assignment.

```
➜ fades --version
Running 'fades' version 7.0
    Python: sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
    System: Linux-4.14.34-1-lts-x86_64-with-arch
```

Thanks @berelarsenp for the help while debugging

**Comment by gilgamezh** [comment]
Thanks!!!
