### ISSUE TITLE
Mejorar parseo de get_version

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/fades#65]
Rompe por ejemplo cuando pip tira algún mensaje extra.

```
*** fades ***  2015-04-30 17:21:08,885  fades.envbuilder   DEBUG    Installing dependencies for repo 'pypi': requested=[Requirement.parse('requests'),
 Requirement.parse('django')]
*** fades ***  2015-04-30 17:21:08,885  fades.pipmanager   INFO     Installing dependency: requests
*** fades ***  2015-04-30 17:21:08,886  fades.exec         DEBUG    Executing external command: ['/home/gilgamezh/.local/share/fades/ff956136-de8e-4f3
c-85e8-df7044260ee9/bin/pip', 'install', 'requests']
*** fades ***  2015-04-30 17:21:09,365  fades.exec         DEBUG    :: You are using pip version 6.0.8, however version 6.1.1 is available.
*** fades ***  2015-04-30 17:21:09,365  fades.exec         DEBUG    :: You should consider upgrading via the 'pip install --upgrade pip' command.
*** fades ***  2015-04-30 17:21:09,371  fades.exec         DEBUG    :: Collecting requests
*** fades ***  2015-04-30 17:21:09,539  fades.exec         DEBUG    ::   Using cached requests-2.6.2-py2.py3-none-any.whl
*** fades ***  2015-04-30 17:21:09,578  fades.exec         DEBUG    :: Installing collected packages: requests
*** fades ***  2015-04-30 17:21:10,031  fades.exec         DEBUG    :: 
*** fades ***  2015-04-30 17:21:10,129  fades.exec         DEBUG    :: Successfully installed requests-2.6.2
*** fades ***  2015-04-30 17:21:10,208  fades.pipmanager   DEBUG    getting installed version for requests
Traceback (most recent call last):
  File "bin/fades", line 45, in <module>
    main.go(version, sys.argv)
  File "/home/gilgamezh/code/fades/fades/main.py", line 106, in go
    venv_data, installed = envbuilder.create_venv(requested_deps)
  File "/home/gilgamezh/code/fades/fades/envbuilder.py", line 100, in create_venv
    installed[repo][project] = mgr.get_version(project)
  File "/home/gilgamezh/code/fades/fades/pipmanager.py", line 64, in get_version
    version = p.stdout.readlines()[2].decode('utf-8').strip().split()[1]
IndexError: list index out of range
 ✘  ~/code/fades   interactive  /home/gilgamezh/.local/share/fades/ff956136-de8e-4f3c-85e8-df7044260ee9/bin/pip show requests
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
---
Name: requests
Version: 2.6.2

```

**Comment by gilgamezh** [comment]
Posible solución: agregar *--disable-pip-version-check*

``` 
 ~/code/fades   interactive  /home/gilgamezh/.local/share/fades/ff956136-de8e-4f3c-85e8-df7044260ee9/bin/pip show requests --disable-pip-version-check
---
Name: requests
Version: 2.6.2
Location: /home/gilgamezh/.local/share/fades/ff956136-de8e-4f3c-85e8-df7044260ee9/lib/python3.4/site-packages
Requires: 
 ~/code/fades   interactive  /home/gilgamezh/.local/share/fades/ff956136-de8e-4f3c-85e8-df7044260ee9/bin/pip show requests                        
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
---
Name: requests
Version: 2.6.2
Location: /home/gilgamezh/.local/share/fades/ff956136-de8e-4f3c-85e8-df7044260ee9/lib/python3.4/site-packages
Requires: 
```
