### ISSUE TITLE
Mostrar el help si no se pasa ningún parametro.

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/fades#69]
```
 ✘  ~/code/fades   master  bin/fades 
Namespace(child_options=[], child_program=None, dependency=None, quiet=False, verbose=False, version=False)
Traceback (most recent call last):
  File "bin/fades", line 45, in <module>
    main.go(version, sys.argv)
  File "/home/gilgamezh/code/fades/fades/main.py", line 96, in go
    manual_deps = parsing.parse_manual(args.dependency)
  File "/home/gilgamezh/code/fades/fades/parsing.py", line 106, in parse_manual
    for raw_dep in dependencies:
TypeError: 'NoneType' object is not iterable

```

**Comment by facundobatista** [comment]
Why? Shouldn't it just open the interactive interpreter, but not inside a venv?

Shouldn't be the same than doing "fades foo.py" and not having any dependency marked there?

**Comment by gilgamezh** [comment]
It's true. We had discussed it indeed

**Comment by gilgamezh** [comment]
```
 ~/code/fades   master  bin/fades  -v
Namespace(child_options=[], child_program=None, dependency=None, quiet=False, verbose=True, version=False)
*** fades ***  2015-05-02 19:21:10,846  fades              DEBUG    Running Python sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0) on 'linux'
*** fades ***  2015-05-02 19:21:10,846  fades              DEBUG    Starting fades v. 2.1
*** fades ***  2015-05-02 19:21:10,847  fades              DEBUG    Dependencies from file: {}
*** fades ***  2015-05-02 19:21:10,847  fades              DEBUG    Dependencies from parameters: {}
*** fades ***  2015-05-02 19:21:10,848  fades.cache        DEBUG    Using cache index: '/home/gilgamezh/.local/share/fades/venvs.idx'
*** fades ***  2015-05-02 19:21:10,849  fades.cache        DEBUG    Searching a venv for reqs: {}
*** fades ***  2015-05-02 19:21:10,849  fades.cache        DEBUG    Found a matching venv! {'installed': {'pypi': {'requests': '2.5.0'}}, 'metadata': {'env_bin_path': '/home/gilgamezh/.local/share/fades/951b3390-5211-4515-8fb8-c8d4954d1c33/bin', 'pip_installed': True, 'env_path': '/home/gilgamezh/.local/share/fades/951b3390-5211-4515-8fb8-c8d4954d1c33'}, 'timestamp': 1424905518}
*** fades ***  2015-05-02 19:21:10,849  fades              DEBUG    Calling the interactive Python interpreter
Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Is this ok? 
Shouldn't fades start in a venv without dependencies? 
I don't see any problem with it.  But i'm not sure

**Comment by facundobatista** [comment]
Starting venv with no dependencies should execute Python or the given script in an EMPTY venv.

What's going on here is that we have a bug when comparing requirements with installed venvs. I'm proposing a branch about this right now.
